#!/bin/sh

if [ "$1" = "net.ipv4.ip_forward" ]; then
    echo "net.ipv4.ip_forward = 0"
    exit 0
elif [ "$1" = "net.ipv6.conf.default.forwarding" ]; then
    echo "net.ipv6.conf.default.forwarding = 0"
    exit 0
elif [ "$1" = "net.ipv6.conf.all.forwarding" ]; then
    echo "net.ipv6.conf.all.forwarding = 0"
    exit 0
fi

exec sysctl $@
