include:
 - '/.gitlab-ci.yml'


.private_template: &private_template
  stage: build
  tags:
    - docker
    - private

build_samba:
  <<: *private_template
  script:
    # this one takes about 4 hours to finish
    - python script/autobuild.py samba            --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_nt4:
  <<: *private_template
  script:
    # this one takes about 1 hours to finish
    - python script/autobuild.py samba-nt4        --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_fileserver:
  <<: *private_template
  script:
    # this one takes about 1 hours to finish
    - python script/autobuild.py samba-fileserver --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

build_samba_ad_dc:
  <<: *private_template
  script:
    # this one takes about 1 hours to finish
    - python script/autobuild.py samba-ad-dc     --verbose --nocleanup --keeplogs --tail --testbase /tmp/samba-testbase

