language: c
dist: trusty

sudo: true

cache: ccache

# Everything except samba and ctdb (long tests)
env:
  - TASK=samba-xc
  - TASK=samba-ctdb
  - TASK=samba-libs
  - TASK=samba-static
  - TASK=samba-o3
  - TASK=samba-none-env
  - TASK=samba-nopython
  - TASK=samba-systemkrb5
  - TASK=samba-nt4
  - TASK=samba-fileserver
  - TASK=samba-ad-dc
  - TASK=samba-ad-dc-2
  - TASK=ldb
  - TASK=tdb
  - TASK=talloc
  - TASK=replace
  - TASK=tevent
  - TASK=pidl

# Fail everything after the first job fails
matrix:
  fast_finish: true

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install --assume-yes acl attr autoconf bind9utils bison build-essential ccache curl debhelper dnsutils docbook-xml docbook-xsl emacs24-nox flex gdb git htop jed krb5-user libacl1-dev libaio-dev libarchive-dev libattr1-dev libblkid-dev libbsd-dev libcap-dev libcups2-dev libgnutls-dev libgpgme11-dev libjansson-dev libjson-perl libldap2-dev liblmdb-dev/trusty-backports libncurses5-dev libpam0g-dev libparse-yapp-perl libpopt-dev libreadline-dev linux-tools-generic lmdb-utils/trusty-backports nettle-dev perl perl-modules pkg-config psmisc python3-dev python3-dnspython python3-gpgme python3-markdown python3-matplotlib python-all-dev python-crypto python-crypto python-dbg python-dev python-dnspython python-gpgme python-markdown python-novaclient python-pexpect rng-tools screen tshark xsltproc zlib1g-dev
 - sudo apt-get install --assume-yes binutils-gold
 - sudo update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.gold" 20
 - sudo update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.bfd" 10
 - sudo update-alternatives --set ld /usr/bin/ld.gold

script:
 - if [ $TASK = "pidl" ]; then
    git fetch --unshallow;
   fi
 - ./script/autobuild.py --tail --testbase=/tmp $TASK
